endpoints:
    - conditions:
        - '[STATUS] == 200'
        - '[RESPONSE_TIME] < 3000'
      group: Panel SkyPanel
      interval: 1m
      name: Panel Principal
      url: http://0.0.0.0:8080/api/config
storage:
    type: memory
ui:
    dashboard-heading: Panel de Monitoreo
    dashboard-subheading: Monitorea el estado de tus servicios en tiempo real
    header: Aether Panel
    title: Aether Panel - Uptime Monitor
web:
    address: 0.0.0.0
    port: 8081
